version: '3.8'

services:
  airflow-standalone:
    image: apache/airflow:2.8.1-python3.11
    container_name: airflow-tickets-orchestrator
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=utc
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: standalone
    restart: unless-stopped
